### ISSUE TITLE
2015.hacknotts.com/ domain not responding

### ISSUE THREAD

**Issue by lukeg101** [HackSocNotts/hacknotts.com#23]
Some time ago @jamietanna and @harrymt set up the subdomain pointing to the 2015 variation of the HackNotts site. This no longer responds, has somebody taken it down?

For the sake of legacy and portfolios, I think it would be nice if each committee/year had its own subdomain set up on the website (in the form _year_.hacknotts.com) then we can refer to it as needed :)

EDIT: italics on Year for domain

**Comment by jamietanna** [comment]
Not taken down, but was not re-setup after I had some issues recently on my VPS that was hosting it.

I'd say for posterity it's not always going to be there, as it requires the exec to have it hosted somewhere, which may not always be possible.

I know there was talk of getting space on a CS school server to host sites, is there an update on that @exec?

**Comment by lukeg101** [comment]
agreed RE posterity point. Hopefully CS servers would mitigate the issue at least for now.

Alternatively, if most of the site elements are static we could host on a HackSoc org GitHub pages site or something similar (GitLab?). This would mitigate cost (I think), and school dependency

**Comment by jamietanna** [comment]
Unfortunately both GitLab and GitHub pages offerings only permit a single site per repo, so either it would require having multiple repos, or to have them hosted some other way.

I found this recently when the WIT sites moved and I had some dropped links, but fortunately were archived on web.archive.org so I could at least have a permalink.

**Comment by lukeg101** [comment]
Currently, the HN and HackSoc website repos are separate (see HackSoc org repos); did you mean one site per org?

Alternatively, we could go for one monolithic domain with subdomains. E.g.
- hacksocnotts.co.uk: main site 
- hacknotts.hacksocnotts.co.uk: hackathon subsite (currently it's not a separate entity like WiT so would be ok)
-We could take it a step further and have 2015.hacknotts.hacksocnotts.co.uk but that might look a little gross (and there are probably better conventions I don't know about)

**Comment by jamietanna** [comment]
> Unfortunately both GitLab and GitHub pages offerings only permit a single site per repo

Ie to host 2015.hacknotts.com you'd need a repo for 2015.hacknotts.com, and one for 2016, etc. This fragmentation makes it harder for maintaining shared code, as well as making it harder to see how much someone has contributed over the year(s) to the sites

**Comment by lukeg101** [comment]
I see, thanks for clarifying. That does suck, a lot.

**Comment by harrymt** [comment]
@jamietanna @lukeg101 I have done this with previous versions of my website in a format that works quite well. They are not subdomained, but simply at another repo and accessed via harrymt.com/SiteYYYY e.g.

- www.harrymt.com/Site2016 (https://github.com/harrymt/Site2016)
- www.harrymt.com/site2015 (https://github.com/harrymt/Site2015)

I think this would be a great method of storing old versions, whenever someone wants to rebrand a new year, create a new repo hacknotts2018 or something.

@lukeg101 if you wanted to, you could always use this method yourself, by forking / cloning the hacknotts website into a repo and activating github pages on it, then access it via e.g. lukeg101.github.io/hacknotts
