### ISSUE TITLE
Link to `uk.mlh.io` doesn't resolve

### ISSUE THREAD

**Issue by jamietanna** [HackSocNotts/hacknotts.com#8]
It looks like the MLH address from the site, http://uk.mlh.io doesn't resolve. Pointing this to the right address would be appreciated.

**Comment by ericorruption** [comment]
@jamietanna Is changing the link to http://mlh.io sufficient?

**Comment by jamietanna** [comment]
Looks like something that @Bericender or @rwdrich can comment on.

**Comment by Casper-Oakley** [comment]
Closed, changed URL to http://mlh.io under direction from @rwdrich
